name: Deploy to Production Website
on:
  push:
    branches:
      - master
jobs:
  BuildCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./public
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Build
        working-directory: ./public
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: React-SPA
          path: ./public/dist

  ReleaseProject:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    needs: BuildCode
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: React-SPA
          path: ./public/dist
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRSE_AA04E }}
          channelId: live
          projectId: trse-aa04e
          entryPoint: .
          expires: 7d
          firebaseToolsVersion: latest
